### ISSUE TITLE
Single domain class per SObject type.

### ISSUE THREAD

**Issue by torynet** [apex-enterprise-patterns/fflib-apex-common#153]
We've been in the process of implementing AEP for a while now. We really appreciate everything that it does for us and all of the hard work that has been put into implementing it. So, thank you to all the contributors.

The fact that the application factory composition root bases it's domain class selection upon SObject type alone, allows for but a single domain class per SObject type. As I get deeper into implementing some of our domain, it occurs to me that our Salesforce configuration really suggests that some SObjects should have pretty vastly different behaviors based upon record type. It seems to me that we should probably have a small interface hierarchy based on record type. With the current implementation of the application factory, the only way I can really see to manage the situation, is to put all the methods for what would have been different classes into one. Then one must write record type checks into all of the methods to ensure they don't get used on the wrong type of records.

Has anyone else ever considered such a situation? It got me thinking about how the application factory could handle multiple different types for one SObject type. I had the thought that perhaps one could provide the application factory with the interface one is looking for an implementation of (similar to the service factory), rather than just extracting the SObject type from the records. That would mean some significant changes or at least additions to the application factory though. 

Am I not seeing some simpler solution? Is this not a problem for anyone else? Maybe other people's orgs don't have single SObjects that represent very similar data but vastly different behavior?

Any thoughts or suggestions would be greatly appreciated.
Thanks,
Tory Netherton

**Comment by marktroupe** [comment]
Yes we're the same, and have just started implementing a solution for this, after realizing the sprinkling domain classes with record type Id checks isn't the best solution.

Our new approach is basically to implement all logic that would otherwise go straight into the domain classes in a seperate 'business logic' layer. This way we have a 'business logic' class per sObject and then per record type (or grouping of record types).

We are implementing our own factory style code to filter records based on record type up front.

**Comment by Telarian** [comment]
@marktroupe I guess I don't really understand your solution.

I've been thinking about adjusting the fflib_Application.DomainFactory to do one of two things. It could either draw the record type name out of the SObject just as it does the SObject type and compare it against a more complex structure that allows both SObject type and the record type name (as stored in an enum say) to determine constructor class rather than just SObject type (currently it uses a map of SObject type to constructor class). Or, it could just expect the developer to pass along the interface for which it will be providing an implementation, just as the service factory does.

The first option has the advantage of being very easy on the "end developer" although it does require the domain class developer to maintain an enum of record type names in the application factory as well as an even more complex map. It has the disadvantage of being tied quite strictly to the record type as the means of differentiation between different domain classes.

The second option has the advantage of being somewhat simpler to maintain at the application factory level and the advantage of being more flexible in terms of differentiation. It has the disadvantage of forcing the "end developer" to always call for the particular interface that is required.

On the other hand, the end developer really has to know what record type is being handled and use appropriate selector methods anyway, or they will just get errors (presumably the application factory will have to throw an exception if you are using this method and you pass it a list with more than one record type in it).

In order to make the whole thing compatible whether you choose to use this "n domain classes per SObject type" variation or not, indicates that it will have to be alongside what already exists. I'm thinking just another separate domain factory class with a different name, that you could use as an alternative to DomainFactory. Then that makes me think that perhaps these things should just be a couple of different implementations of an IDomainFactory interface but my head starts to hurt when it goes down that rabbit hole.

Anyone else have any thoughts on this?

**Comment by afawcett** [comment]
I actually recall talking to @up2go-rsoesemann [about this](https://github.com/financialforcedev/df12-apex-enterprise-patterns/issues/4) a while back. I confess neither of us appear to have updated the issue to share the results. So I'm hoping Robert can share what he ended up doing, as i don't fully recall. 

As i recall though and thinking about this again. The problem with routing work to different domain classes per record type is that it may result in less bulkified or optimal use of queries and DML. 

For example in a Apex Trigger context, if 200 records are updated for an object with 4 record types, their is a potential for up to 4 domain class methods to be called. Each would work with a subset of the 200 records and may duplicate work. 

I guess this comes down to the key thought of this discuss. It is that its the same object but the record types mean that the processing is so radically different that the bulkification erosion worry is less of a concern, since the queries and dml's performed by the distinct domain classes will all target different objects anyway?

If this is not the case, kind of handling this in the framework to me gives the developer a false sense of comfort that bulkification does not need to be considered. Thus as much as i agree considering it explicitly in the object domain class is a pain, it does at least put the responsibility to the developer to think about the broader implications in Apex Trigger scenarios where the record types can vary.

All this said, i can imagine supporting both, the classic low level model (of build your own approach / handle it manually) and some kind of DomainFactory approach as described above that allows the declaration of the routing and the framework handles that. The later would likely need to be well documented and positioned though.

@marktroupe really interested on your take on this and if the above use case is valid for you? Also @up2go-rsoesemann keen to get your thoughts.

Thanks everyone, great discussion!

**Comment by up2go-rsoesemann** [comment]
@afawcett we never solved this at a sophisticated library level. We never had to cover multiple record types. We just only wanted to handle a few of them in a single class.

In our products, Record types are a way customers extend our package so we have to handle this generically. The current fflib is perfect for that. I understand @Telarian's use case but also your argumentation that splitting by RT would somewhat harm the bulkification main goal of Domain classes.

**Comment by marktroupe** [comment]
@afawcett 

> For example in a Apex Trigger context, if 200 records are updated for an object with 4 record types, their is a potential for up to 4 domain class methods to be called. Each would work with a subset of the 200 records and may duplicate work.

This is the main reason we decided not to go with multiple domain classes. 

We have a big problem with Too Many SOQLs and decided that by keeping one domain class we can 'cache' query results inside the domain instance, eg. for Opportunity we cache parent Accounts, child OppContactRoles and other custom objects, and pass these lists to other more record type specific methods and classes that contain the business logic.

In one case we've developed a 'business layer' base class, OpportunitiesBL.cls, and then extended it into record type specific classes, OpportunitiesBL_<RT1>.cls, OpportunitiesBL_<RT2>.cls. This way we store common functionality in the base class and override methods where the logic is different. The business layer classes are only querying directly where absolutely necessary. These are instantiated from the domain class and the commonly used Lists<*> are passed in up front.

**Comment by Telarian** [comment]
Thank you all for the input. @marktroupe I believe I fully understand your architecture now. Thanks for the clarification.

I'm quite averse to just "sprinkling the domain methods with record type checks" as @marktroupe put it. You end up with messy intermixed code and many methods on the domain class that have no application for the type you are dealing with in any given instance.

I'm not sure how I feel about the (as I think of it) "domain class as a thin facade over a variety of true domain classes" concept either. I do very much like the simplicity of always being able to just detect the record types you have been given and hand the processing off to whatever sub-class is appropriate. The issue I see with this, is that the end developer still gets all those meaningless methods. They never get the opportunity to just think of a simple clear object. I guess it just seems like it makes for a very messy interface with many methods, where in any given case most of them will result in an error.

For us, in most instances, we would not be handling two SObjects of differing record type at the same time anyway, and I don't see that much soql proliferation coming of it. In the simpler cases (like multiple Opportunity types where you want the domain classes to have access to the parent Account) we would just query with those parent fields via a selectByIdWithAccounts or case specific e.g. selectByIdForTransfer selector method, in the first place and expect them to be there. For more complex queries, I honestly can't really imagine ever having one that applied to multiple record types in the first place. In our case, it definitely feels to me that like @afawcett said, we have less concern about bulkification erosion than we do about code clarity.

We have been thinking of a sort of "parent" domain class that we could use to handle more generic methods where they do exist. So, I might have an AccountClients.cls and AccountAgencies.cls for handling two different Account record types. But then I might also have an Accounts.cls for handling that shared behavior and the child types could either compose or inherit that functionality. I guess it's very similar to what @marktroupe has been doing except that we haven't put it back a layer behind the standard domain class.

All of this makes me wonder if I couldn't use something very similar to what @marktroupe has suggested except that what he refers to as his "business layer" would just be my domain classes as I have described, and I could put a routing layer between the trigger and them. I also can envision just returning a list from the new domain factory and letting the trigger iterate it. That would of course require a small change in other places where the domain factory is used, but it would be small and since this is all "in addition" it breaks nothing.

I realize that none of that would actually prevent soql proliferation the way the @marktroupe solution does, and it would have to be made very clear to the developer that this should be considered quite carefully when using it. I don't think it would be difficult for us to use appropriately though, and I feel like the interface exposed to the end developer is much cleaner.

Please continue to poke holes in my understanding. I'm very eager to see the error of my ways. I imagine being an enterprise developer rather than an ISV gives me a rather different point of view. I probably take things for granted more than I should due to my insulated environment.

Thanks for enlightening me.

**Comment by forcecreators** [comment]
Hi Guys! Our organization faced a similar issue, and I wanted to share how I was able to resolve this issue without having to modify any of the underlying API. Here's what I came up with.

Every domain class that we create extends the following class: 

```
public virtual class DomainObject extends fflib_SObjectDomain {
	
	public String recordTypeFilter {get;set;}
	public List<SObject> newRecords {get;set;}
	public Map<Id, SObject> oldRecords {get;set;}

	public DomainObject(List<sObject> sObjectList) {
               super(sObjectList);
	       newRecords = records;

        }

	public void setFilter(String recordTypeName) {

		List<SObject> mapOverride = new List<SObject>();

		for(sObject o : newRecords) {

			String recordTypeIdFilter = (o.getSObjectType().getDescribe()).getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
			String sObjRecType = o.get('RecordTypeId').ToString();

			if(recordTypeIdFilter == sObjRecType) {
				mapOverride.add(o);
			}
		}

		newRecords = mapOverride;
	}

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new DomainObject(sObjectList);
        }
    }

}
```

So our domain class ends up looking like this:
```
public virtual class Tasks extends DomainObject  {
	
	public Tasks(List<Task> sObjectList) {
             super(sObjectList);
         }

	public virtual override void onBeforeUpdate(Map<Id,SObject> oldRecords) {

	}

	public virtual void checkMinimumChars(Map<Id,SObject> oldRecords) {
		
		for(Task t : (List<Task>) newRecords) {
			
			Task oldTask = (Task) oldRecords.get(t.Id);
			Boolean wasClosed = (oldTask.Status == 'Follow-up' && t.Status == 'Completed');

			if(wasClosed && (t.Description == null || t.Description.length() < 3)) {
				t.addError('Please enter a comment');
			}

		}

	}

	public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Tasks(sObjectList);
        }
    }

}
```

Now for the "Record Type" domain object. The trick is to make the domain class virtual and call the parents setFilter method. setFilter takes the recordtype's name.
```
public class SalesTasks extends Tasks  {
	
	public SalesTasks(List<Task> sObjectList) {
                super(sObjectList);
		super.setFilter('Sales Task');
        }

	public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
		checkMinimumChars(oldRecords);
	}


	public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new SalesTasks(sObjectList);
        }
    }

}
```


And finally, our trigger handler: 
```
trigger ccTaskTrigger on Task (before insert,after insert, before update, after update)  { 
	
	fflib_SObjectDomain.triggerHandler(Tasks.class);
	fflib_SObjectDomain.triggerHandler(SalesTasks.class);
	fflib_SObjectDomain.triggerHandler(QuoteComments.class);
	fflib_SObjectDomain.triggerHandler(RenewalComments.class);

}
```

So essentially, what I've done here is create a piece of middle-man between the fflib_SObjectDomain class and our domain class. The super.setFilter removed any record types that the trigger should not process. 

This merely a proof of concept, but I hope it helps out anyone else who has a similar need :) 

Thanks!
Matt

**Comment by reignman5** [comment]
> Hi Guys! Our organization faced a similar issue, and I wanted to share how I was able to resolve this issue without having to modify any of the underlying API. Here's what I came up with.
> 
> Every domain class that we create extends the following class:
> 
> ```
> public virtual class DomainObject extends fflib_SObjectDomain {
> 	
> 	public String recordTypeFilter {get;set;}
> 	public List<SObject> newRecords {get;set;}
> 	public Map<Id, SObject> oldRecords {get;set;}
> 
> 	public DomainObject(List<sObject> sObjectList) {
>                super(sObjectList);
> 	       newRecords = records;
> 
>         }
> 
> 	public void setFilter(String recordTypeName) {
> 
> 		List<SObject> mapOverride = new List<SObject>();
> 
> 		for(sObject o : newRecords) {
> 
> 			String recordTypeIdFilter = (o.getSObjectType().getDescribe()).getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
> 			String sObjRecType = o.get('RecordTypeId').ToString();
> 
> 			if(recordTypeIdFilter == sObjRecType) {
> 				mapOverride.add(o);
> 			}
> 		}
> 
> 		newRecords = mapOverride;
> 	}
> 
>     public class Constructor implements fflib_SObjectDomain.IConstructable {
>         public fflib_SObjectDomain construct(List<SObject> sObjectList) {
>             return new DomainObject(sObjectList);
>         }
>     }
> 
> }
> ```
> 
> So our domain class ends up looking like this:
> 
> ```
> public virtual class Tasks extends DomainObject  {
> 	
> 	public Tasks(List<Task> sObjectList) {
>              super(sObjectList);
>          }
> 
> 	public virtual override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
> 
> 	}
> 
> 	public virtual void checkMinimumChars(Map<Id,SObject> oldRecords) {
> 		
> 		for(Task t : (List<Task>) newRecords) {
> 			
> 			Task oldTask = (Task) oldRecords.get(t.Id);
> 			Boolean wasClosed = (oldTask.Status == 'Follow-up' && t.Status == 'Completed');
> 
> 			if(wasClosed && (t.Description == null || t.Description.length() < 3)) {
> 				t.addError('Please enter a comment');
> 			}
> 
> 		}
> 
> 	}
> 
> 	public class Constructor implements fflib_SObjectDomain.IConstructable {
>         public fflib_SObjectDomain construct(List<SObject> sObjectList) {
>             return new Tasks(sObjectList);
>         }
>     }
> 
> }
> ```
> 
> Now for the "Record Type" domain object. The trick is to make the domain class virtual and call the parents setFilter method. setFilter takes the recordtype's name.
> 
> ```
> public class SalesTasks extends Tasks  {
> 	
> 	public SalesTasks(List<Task> sObjectList) {
>                 super(sObjectList);
> 		super.setFilter('Sales Task');
>         }
> 
> 	public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
> 		checkMinimumChars(oldRecords);
> 	}
> 
> 
> 	public class Constructor implements fflib_SObjectDomain.IConstructable {
>         public fflib_SObjectDomain construct(List<SObject> sObjectList) {
>             return new SalesTasks(sObjectList);
>         }
>     }
> 
> }
> ```
> 
> And finally, our trigger handler:
> 
> ```
> trigger ccTaskTrigger on Task (before insert,after insert, before update, after update)  { 
> 	
> 	fflib_SObjectDomain.triggerHandler(Tasks.class);
> 	fflib_SObjectDomain.triggerHandler(SalesTasks.class);
> 	fflib_SObjectDomain.triggerHandler(QuoteComments.class);
> 	fflib_SObjectDomain.triggerHandler(RenewalComments.class);
> 
> }
> ```
> 
> So essentially, what I've done here is create a middle-man between the fflib_SObjectDomain class and our domain class. The super.setFilter removes any record types that the trigger should not process for that specific record type.
> 
> This merely a proof of concept, but I hope it helps out anyone else who has a similar need :)
> 
> Thanks!
> Matt

@forcecreators 
Hey,

we are facing the same problem. Is this the solution you stuck with or did you find anything else?

Thanks for your help!

**Comment by daveespo** [comment]
See https://github.com/apex-enterprise-patterns/fflib-apex-common/discussions/337 for a similar concept by @wimvelzeboer
