### ISSUE TITLE
Extend registerDelete to include emptyRecycleBin option

### ISSUE THREAD

**Issue by cropredyHelix** [apex-enterprise-patterns/fflib-apex-common#238]
Although one can work around this with registerWork, it would be convenient to have a 

    void registerDeleted(SObject record, Boolean emptyRecycleBin) ;

    void registerDeleted(SObject[] records, Boolean emptyRecycleBin);

where `commitWork()` empties the recycleBin of all Ids so registered. Default for `emptyRecycleBin` would be false.

The utility of this occurs in batchables that do mass deletes

**Comment by wimvelzeboer** [comment]
Hi @cropredyHelix,
I raised a pull-request with a change to add this functionality. Instead of using a Boolean parameter I added it to the methods name `registerPermanentlyDeleted`. I also added `registerEmptyRecycleBin` which can be used for files that are already in the recycle bin.
Hope you like it.

**Comment by cropredyHelix** [comment]
Cool - works for me ...note that my PRs fail on the travis CI build with some Java version issue; should be interesting to see if yours works better

**Comment by wimvelzeboer** [comment]
@afawcett @cropredyHelix I think we can close this issue as the pull-request is now merged, right?
