### ISSUE TITLE
ffflib_SObjectDescribe performance on API 44+

### ISSUE THREAD

**Issue by nawforce** [apex-enterprise-patterns/fflib-apex-common#275]
At API 44 something was changed in how SObjectType.getDescribe works internally that had a noticeable impact on the performance of 'public static fflib_SObjectDescribe getDescribe(Schema.SObjectType token)', see https://success.salesforce.com/issues_view?id=a1p3A000001RXBZQA4 for details. 

Much of performance loss can be recovered in later API versions by using the new SObjectDescribeOptions.DEFERRED option. For more information on this see, https://www.ca-peterson.com/apex/2020/01/21/apex-describe-calls-what-you-need-to-know.html.

**Comment by ImJohnMDaniel** [comment]
@capeterson  -- Just curious if you are aware of this or have any input.

**Comment by Javwadazeem** [comment]
@nawforce @afawcett , I think we have recently upgraded classes API v47. I am using "SObjectDescribeOptions" in multiple scenarios and its remarkably fast. I am sure we can implement this in securityUtils class. I have updated one method to test and CPU time dropped from 30ms to 3ms.
For example:-
`public static void checkObjectIsInsertable(SObjectType objType)
    {
    	if (BYPASS_INTERNAL_FLS_AND_CRUD)
            return;
    	if (!objType.getDescribe(SObjectDescribeOptions.DEFERRED).isCreateable())
    	{
    		throw new CrudException(OperationType.CREATE, objType);
    	}
    }
    `

**Comment by nawforce** [comment]
@Javwadazeem Might be more rational to update fflib_SObjectDescribe & have fflib_SecurityUtils use it, not sure why this was not done earlier. I have heard about some changes in behaviour when you use SObjectDescribeOptions.DEFERRED so some might see minor issues but you would really have to dig deep through the blog post on this to have much chance of understanding them.

**Comment by capeterson** [comment]
@nawforce the way fflib_QueryFactory at least uses describes should be safe with deferred loading generally - and for the cases where it isn't the caching in fflib_SObjectDescribe would already make it subject to the issues.  I think Queryfactory is the most intense about complex relationships since it makes use of things like getReferenceTo() so heavily - but maybe I'm missing another consumer that's higher risk. Don't think so - but possible.

The issues you'd see with deferred are more often with picklists - particularly Einstein related ones that are dynamically generated in ways that the deferred handling can't automatically emulate fully. Internally, deferred mode DescribeSObjectResult instances keep a reference to the platform's internal security state of Apex at the moment of instantiation - and restore it when doing lazy loads on properties for the first time. The risk is that in the most obscure and arcane of cases there may be some aspect of the context where the DescribeSObjectResult was created that isn't fully tracked and restored by this. If you keep the instance within the same namespace and at the same API version - like what the caching fflib_SObjectDescribe does - the chance of there being a material difference that's not captured and restored this way decreases dramatically - and it isn't super high to start with.

I'd support this change, since it doesn't materially alter the potential surface area for describe quirkyness above the existing baseline, but would improve perf by not spending time doing things like generating child relationship data for all fields - even if it's not used.

**Comment by nawforce** [comment]
@capeterson Thanks for clarifying where this might be an issue. The area I mentioned earlier turned out to be with describes called before & after System.runAs but there is an easy workaround of calling fflib_SObjectDescribe.flushCache() before each runAs() and that should have been done anyway.

**Comment by daveespo** [comment]
I'm closing this thread because I believe it to be the same resolution as #281
