### ISSUE TITLE
Uow supports dynamical add SObject types

### ISSUE THREAD

**Issue by jairzh** [apex-enterprise-patterns/fflib-apex-common#285]
To let SObjectUnitOfWork know which sObjects need to be handled that should past them into the constructor when new SObjectUnitOfWork, is there a way to let different methods dynamical add SObject types when sharing one instance uow in a transaction?

**Comment by afawcett** [comment]
@jairzh not really - this would also go against the principles of it being a shared resource - since behavior could potentially change depending on the code path execution - which starts to create some complex debug scenarios IMHO. What you could do is implement a discovery pattern - to ask your services for the sobject types they wanted to be included then proceed to execute.
