### ISSUE TITLE
Salesforce Internal error on Trigger.new when using fflib_SObjectDomain on BatchApexErrorEvent

### ISSUE THREAD

**Issue by rsoesemann** [apex-enterprise-patterns/fflib-apex-common#301]
SObjectDomain Trigger Handlers successfully works for Custom Platform events but not for native ones like  `BatchApexErrorEvent`. Why is that so?

Here is my trigger

    trigger BatchApexErrorEvents on BatchApexErrorEvent (after insert) {
        fflib_SObjectDomain.triggerHandler(BatchApexErrorEvents.class);
    }

which delegates to this `fflib_SObjectDomain`

    public with sharing class BatchApexErrorEvents extends fflib_SObjectDomain {

        // CONSTRUCTOR

        public BatchApexErrorEvents(List<BatchApexErrorEvent> events) {
            // .. Fails in super
            super(events);
        }

        // PUBLIC

        public override void onAfterInsert() {
            // .. Never reaches this line
        }

        // INNER

        public class Constructor implements fflib_SObjectDomain.IConstructable {
            public fflib_SObjectDomain construct(List<SObject> sObjectList) {
                return new BatchApexErrorEvents(sObjectList);
            }
        }
    }

It fails in `**fflib_SObjectDomain.cls**`  with `Internal Salesforce.com Error` when `Trigger.new` is called in those lines:

	public static void triggerHandler(Type domainClass)
	{		
		// Process the trigger context
		if(System.Test.isRunningTest() && Test.Database.hasRecords())
		{
			// If in test context and records in the mock database delegate initially to the mock database trigger handler
			Test.Database.testTriggerHandler(domainClass);
		}
		else
		{
			// Process the runtime Apex Trigger context
			triggerHandler(domainClass,
				Trigger.isBefore,
				Trigger.isAfter,
				Trigger.isInsert,
				Trigger.isUpdate,
				Trigger.isDelete,
				Trigger.isUnDelete,
				Trigger.new, 
				Trigger.oldMap);
		}
	}

**Comment by ImJohnMDaniel** [comment]
G'day @rsoesemann -- Quick related question.  When you are are working with PEs/CDCs, what are the typical things that you are doing with those messages?

**Comment by rsoesemann** [comment]
@ImJohnMDaniel  Creating copies in custom objects, send out custom notifications, start a batch retry as described in Andy Fawcetts blog,...

**Comment by ImJohnMDaniel** [comment]
Hey @rsoesemann, thanks for the reply and that is exactly what I expected.

My point in that question is that, the more I deal with PEs/CDCs, the more that I realize that we should not develop domain classes for them at all.  They are not records.  They are "messages".

Every use case you described is best handled by a service class.  Every use case that I have come across with PEs/CDCs can be handled the same way you would handle a custom REST endpoint.  A custom REST endpoint typically would call a service tier method.

One of the primary purposes of domain classes is to "apply business logic specific to the SObject".  The Apex Common trigger handler framework was built with this in mind and that is why you handle logic on SObjects from the domain classes.  The PEs/CDCs are not like SObjects because you cannot "apply any business logic" to them.  You cannot "change" the "message" in a PE/CDC.  You can only react to them (like you would with a custom REST endpoint).

I find more and more that, because the only way to "subscribe to a PE/CDC message" in Apex is via a "trigger", developers are naturally gravitating towards the idea that "the PE/CDC trigger must be handled by a domain class because that is what you do with all other SObjects."  While PE/CDCs are similar to records, they differ enough for me to forgo the creation of a domain object (which would serve no purpose anyway and just be a "pass-through"), and just have the Apex subscriber trigger call a service method directly.

Also, when thinking about PE/CDC Apex Subscriber triggers, it should be noted that the rule of "one trigger per SObject" does not apply to PE/CDC triggers.  That rule was because all of the SObject triggers would be handled in the same execution process and there is a need to deterministically manage all the tasks that result from the DML event.  Multiple SObject triggers could not guarantee this and thus the best practice of "one trigger per SObject with some centralized handler logic" came to be.  PE/CDC triggers differ because they never run in the original execution process.  It is always a separate, independent, execution process.  To make it more interesting, each PE/CDC Apex Subscriber trigger listening to the same EventBus executes in its own separate, execution process.  The old constraint for SObjects does not apply to PEs/CDCs.  Thus, the best practice of "one trigger per SObject" is not required for PE/CDC either.  So, in my opinion, create multiple subscribers that only call a specific service method.

So, you are correct that, for some reason, the Apex Common fflib_SObjectDomain class does not correctly handle standard platform events.  But I submit to you that you should not use it for PEs/CDCs in the first place.

I would love to hear your thoughts (and anyone else's) on this thought.

@afawcett, @daveespo, and @stohn777 -- Any thoughts?

**Comment by daveespo** [comment]
I am in agreement with @ImJohnMDaniel  -- `fflib_SObjectDomain` is serving double duty as a trigger handler pattern and domain encapsulation. This was recently discussed over on #273 and a new proposal is on #300. John's point about one-trigger-per-SObject is also very well made.

If you choose to open a case to find out why standard platform events can't be handled by `fflib_SObjectDomain`, we'd all be curious to hear the explanation Support provides :-P

**Comment by rsoesemann** [comment]
@ImJohnMDaniel I can follow your argumentation but I can also follow mine. ;-) 
Everything that is an SObject and can have triggers should be handled in a central domain class. Not for technical reasons but for maintainability reasons. Feel free to close this.

**Comment by ImJohnMDaniel** [comment]
Sounds good.

One other thought.  Are you able to capture a debug log for the replay debugger?  If so, can you forward it to me for review?  I am curious exactly what line in fflib_SObjectDomain is it failing on.

**Comment by rsoesemann** [comment]
Never used the Replay Debugger. But its failing when calling Trigger.new in https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/46e2e79a9e16939c9e76c51b7b46bc83dc110461/sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls#L410

**Comment by ImJohnMDaniel** [comment]
@rsoesemann, any chance that you could setup a small project to reproduce the issue?
