### ISSUE TITLE
Question: use of getDescribe() in FFLIB_SObjectUnitOfWork

### ISSUE THREAD

**Issue by dsurfleet** [apex-enterprise-patterns/fflib-apex-common#312]
I'm interested in understanding why the unit of work object was implemented with maps of < String, List<sObject> > which requires the code to have a lot of the ".getDescribe().getName()" calls everywhere you want to add a record to one of the maps as well as during initialization. Couldn't the implementation have been done with maps of < sObjectType, List<sObject> > and then you remove the limited overhead the describe calls add?

In the org I'm working in we're planning to use the Application.UnitOfWork.newInstance() approach to create instances of the unit of work class (may not be the best practice, so maybe we have to change that), but that means we've got ~700 objects added to every unit of work instance and the describes add up (200-400 on the CPU time limit depending on cache).

**Comment by dsurfleet** [comment]
@wimvelzeboer I see a nice advantage of waiting as well, if it means we don't have to pre-register what object types will be used in the instance. In my specific case, there is a team of ~50 developers working on this org and developers won't always know what objects are needed in each instance (which is why we're planning to use the Application.UnitOfWork.newInstance() approach).

**Comment by dsurfleet** [comment]
Another approach we could do is String.valueOf(sObjectType) which returns the object name without the describe. I know that possibly could change in the future, but it removes all the overhead of the describe.

**Comment by daveespo** [comment]
To @dsurfleet's question about why you need to define the list of SObjects when constructing an fflib_SObjectUnitOfWork -- order of operations usually matters. If you were able to arbitrarily push new SObject instances into an SOUOW (`registerNew`/`registerDirty`) the call to `commitWork()` would fail some of the time if the Detail object was inserted before the Master object

As for why the internal structure of SOUOW uses Maps keyed on String -- that was a decision made too long ago to try to walk back. Unfortunately they're declared as `protected` so we can't just change the implementation since it would be a breaking change. If you can provide a test script that benchmarks the differences between keying the Maps on String vs SObjectType and it clearly points at the getDescribe().getName() as the hotspot, we can potentially add a map for SObjectType->String that's hydrated when the SOUOW is constructed
